---
# CentOS specific package installations
- include: RedHat.yml
  when: ansible_os_family  == "RedHat"

# Ubuntu specific package installations
- include: Debian.yml
  when: ansible_os_family  == "Debian"
