
---
- name: create /tmp/dog
  file: path="/tmp/dog" state=directory mode=0770 owner=dog group=dog
  become: yes

- name: create /tmp/dog/ssl
  file: path="/tmp/dog/ssl" state=directory mode=0770 owner=dog group=dog
  become: yes

- name: create /tmp/dog/ssl
  file: path="/tmp/dog/ssl" state=directory mode=0700 owner={{ lookup('env', 'USER') }} group={{ lookup('env', 'USER') }}
  connection: local
  delegate_to: 127.0.0.1
  become: no

- name: create ssl conf
  template: dest=/tmp/dog/ssl/ssl.{{ inventory_hostname }}.conf src=templates/ssl.conf.j2
  connection: local
  delegate_to: 127.0.0.1
  become: no

- name: create csr
  shell: openssl req -new -nodes -out /tmp/dog/ssl/{{ inventory_hostname }}.dog.csr -keyout /tmp/dog/ssl/{{ inventory_hostname }}.dog.key -config /tmp/dog/ssl/ssl.{{ inventory_hostname }}.conf -newkey rsa:2048
  connection: local
  delegate_to: 127.0.0.1
  become: no

- name: create instance cert
  shell: openssl ca -batch -config /tmp/dog/ssl/ssl.{{ inventory_hostname }}.conf -notext -in /tmp/dog/ssl/{{ inventory_hostname }}.dog.csr -out /tmp/dog/ssl/{{ inventory_hostname }}.dog.cer -passin file:ca_passphrase.txt
  connection: local
  delegate_to: 127.0.0.1
  become: no

- name: create data dir
  file: path="{{ dog_data_dir }}" state=directory mode=0770 owner=dog group=dog
  become: yes

- name: create data/pki dir
  file: path="{{ dog_data_dir }}/pki" state=directory mode=0770 owner=dog group=dog
  become: yes

- name: create data/pki/private dir
  file: path="{{ dog_data_dir }}/pki/private" state=directory mode=0770 owner=dog group=dog
  become: yes

- name: create data/pki/certs dir
  file: path="{{ dog_data_dir }}/pki/certs" state=directory mode=0770 owner=dog group=dog
  become: yes

- name: copy server.key
  copy: src="/tmp/dog/ssl/{{ inventory_hostname }}.dog.key" dest="{{ dog_data_dir }}/pki/private/server.key" owner=dog group=dog
  become: yes

- name: copy server.crt
  copy: src="/tmp/dog/ssl/{{ inventory_hostname }}.dog.cer" dest="{{ dog_data_dir }}/pki/certs/server.crt" owner=dog group=dog
  become: yes

- name: copy ca.crt
  copy: src=dog-root.cer dest="{{ dog_data_dir }}/pki/certs/ca.crt" owner=dog group=dog
  become: yes
